services:
  app:
    build: .
    image: dongvandat/express-books-app:latest
    ports:
      - "3001:3001"
    env_file:
      - .env.prod
    depends_on:
      - db
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network
      
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin123}
      POSTGRES_DB: ${DB_NAME:-books_db}
    ports:
      - "5433:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_prod_data:
    driver: local

networks:
  app-network:
    driver: bridge