name: Deploy to EC2

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t dongvandat/express-books-app:latest .
          docker push dongvandat/express-books-app:latest

      - name: Pull latest Docker image and restart container
        run: |
          docker pull dongvandat/express-books-app:latest
          docker-compose -f docker-compose.prod.yml down
          docker-compose -f docker-compose.prod.yml up -d